import { motion } from "framer-motion";
import { useNavigate } from "react-router-dom";

import DashboardNavbar from "../components/dashboard/Navbar";
import SplashCursor from "../components/SplashCursor";

export default function InterviewResults() {

  const navigate = useNavigate();

  const overallScore = 91;

  const circumference = 2 * Math.PI * 90;
  const offset =
    circumference -
    (overallScore / 100) * circumference;

  return (
    <div className="min-h-screen bg-black text-white overflow-x-hidden">

        <SplashCursor
            DENSITY_DISSIPATION={4}
            VELOCITY_DISSIPATION={2.2}
            PRESSURE={0.08}
            CURL={2}
            SPLAT_RADIUS={0.12}
            SPLAT_FORCE={3500}
            COLOR_UPDATE_SPEED={8}
            SHADING
            RAINBOW_MODE
            COLOR="#8B5CF6"
        />

      <DashboardNavbar />


      <main className="max-w-6xl mx-auto px-6 pt-36 pb-20">

        {/* Header */}

        <motion.div
          initial={{
            opacity: 0,
            y: 20,
          }}
          animate={{
            opacity: 1,
            y: 0,
          }}
          transition={{
            duration: .5,
          }}
        >

          <p className="text-violet-400 font-medium">
            AI Interview Completed
          </p>

          <h1 className="mt-3 text-5xl font-bold">
            Your Interview Report
          </h1>

          <p className="mt-4 text-zinc-400 max-w-2xl">
            Here's a detailed analysis of your
            interview performance generated by
            FinalRound AI.
          </p>

        </motion.div>

        {/* Hero Section */}

        <div className="grid lg:grid-cols-[1.2fr_1fr] gap-10 mt-14">

          {/* Score Card */}

          <motion.div

            initial={{
              opacity: 0,
              y: 20,
            }}

            animate={{
              opacity: 1,
              y: 0,
            }}

            transition={{
              delay: .15,
            }}

            className="
              relative
              overflow-hidden
              rounded-[36px]
              border
              border-white/10
              bg-white/[0.03]
              backdrop-blur-xl
              p-10
            "

          >

            {/* Glow */}

            <div
              className="
                absolute
                -top-32
                -right-32
                h-72
                w-72
                rounded-full
                bg-violet-500/10
                blur-[120px]
              "
            />

            <div className="relative z-10">

              <p className="text-zinc-500">
                Overall Performance
              </p>

              <div className="flex justify-center mt-10">

                <div className="relative h-64 w-64">

                  <svg
                    className="h-full w-full -rotate-90"
                    viewBox="0 0 220 220"
                  >

                    <circle
                      cx="110"
                      cy="110"
                      r="90"
                      stroke="rgba(255,255,255,.08)"
                      strokeWidth="12"
                      fill="none"
                    />

                    <motion.circle

                      initial={{
                        strokeDashoffset:
                          circumference,
                      }}

                      animate={{
                        strokeDashoffset:
                          offset,
                      }}

                      transition={{
                        duration: 1.5,
                      }}

                      cx="110"
                      cy="110"
                      r="90"
                      stroke="url(#gradient)"
                      strokeWidth="12"
                      strokeLinecap="round"
                      fill="none"
                      strokeDasharray={
                        circumference
                      }
                      strokeDashoffset={offset}

                    />

                    <defs>

                      <linearGradient
                        id="gradient"
                      >

                        <stop
                          offset="0%"
                          stopColor="#8B5CF6"
                        />

                        <stop
                          offset="100%"
                          stopColor="#22D3EE"
                        />

                      </linearGradient>

                    </defs>

                  </svg>

                  <div
                    className="
                      absolute
                      inset-0
                      flex
                      flex-col
                      items-center
                      justify-center
                    "
                  >

                    <span className="text-6xl font-bold">
                      {overallScore}
                    </span>

                    <span className="text-zinc-400 mt-2">
                      /100
                    </span>

                  </div>

                </div>

              </div>

              <div className="text-center mt-8">

                <h2 className="text-3xl font-bold text-green-400">
                  Excellent Performance
                </h2>

                <p className="mt-3 text-zinc-400">

                  You demonstrated strong
                  communication skills and
                  technical understanding
                  throughout the interview.

                </p>

              </div>

            </div>

          </motion.div>

          {/* Quick Summary */}

          <motion.div

            initial={{
              opacity: 0,
              y: 20,
            }}

            animate={{
              opacity: 1,
              y: 0,
            }}

            transition={{
              delay: .3,
            }}

            className="
              rounded-[36px]
              border
              border-white/10
              bg-white/[0.03]
              backdrop-blur-xl
              p-8
            "

          >

            <h2 className="text-2xl font-bold">
              Interview Summary
            </h2>

            <div className="space-y-6 mt-8">

              <div>

                <p className="text-zinc-500 text-sm">
                  Duration
                </p>

                <h3 className="text-2xl font-semibold mt-1">
                  23 mins
                </h3>

              </div>

              <div>

                <p className="text-zinc-500 text-sm">
                  Questions Answered
                </p>

                <h3 className="text-2xl font-semibold mt-1">
                  15 / 15
                </h3>

              </div>

              <div>

                <p className="text-zinc-500 text-sm">
                  Strongest Section
                </p>

                <h3 className="text-2xl font-semibold mt-1">
                  Communication
                </h3>

              </div>

              <div>

                <p className="text-zinc-500 text-sm">
                  Recommendation
                </p>

                <span
                  className="
                    inline-flex
                    mt-2
                    rounded-full
                    bg-green-500/10
                    px-4
                    py-2
                    text-green-400
                    text-sm
                  "
                >
                  Ready for Interviews
                </span>

              </div>

            </div>

          </motion.div>

        </div>

        {/* Performance Breakdown */}
        <div className="grid lg:grid-cols-2 gap-8 mt-10">

  {/* Skill Scores */}

  <div
    className="
      rounded-[32px]
      border
      border-white/10
      bg-white/[0.03]
      backdrop-blur-xl
      p-8
    "
  >

    <h2 className="text-2xl font-bold">
      Skill Breakdown
    </h2>

    {[
      {
        skill: "Communication",
        score: 94,
      },
      {
        skill: "Technical Knowledge",
        score: 88,
      },
      {
        skill: "Problem Solving",
        score: 84,
      },
      {
        skill: "Confidence",
        score: 91,
      },
    ].map((item) => (

      <div
        key={item.skill}
        className="mt-8"
      >

        <div className="flex justify-between mb-2">

          <span>{item.skill}</span>

          <span className="text-violet-400">
            {item.score}%
          </span>

        </div>

        <div className="h-3 rounded-full bg-white/5 overflow-hidden">

          <motion.div

            initial={{
              width: 0,
            }}

            animate={{
              width: `${item.score}%`,
            }}

            transition={{
              duration: 1,
            }}

            className="
              h-full
              rounded-full
              bg-gradient-to-r
              from-violet-500
              to-cyan-400
            "

          />

        </div>

      </div>

    ))}

  </div>

  {/* Strengths */}

  <div
    className="
      rounded-[32px]
      border
      border-white/10
      bg-white/[0.03]
      backdrop-blur-xl
      p-8
    "
  >

    <h2 className="text-2xl font-bold">
      Top Strengths
    </h2>

    <div className="space-y-5 mt-8">

      <div className="rounded-2xl bg-green-500/10 p-5">
        Excellent Communication Skills
      </div>

      <div className="rounded-2xl bg-green-500/10 p-5">
        Strong React Fundamentals
      </div>

      <div className="rounded-2xl bg-green-500/10 p-5">
        Structured Problem Solving
      </div>

    </div>

    <h2 className="text-2xl font-bold mt-12">
      Areas to Improve
    </h2>

    <div className="space-y-5 mt-8">

      <div className="rounded-2xl bg-red-500/10 p-5">
        Improve System Design Concepts
      </div>

      <div className="rounded-2xl bg-red-500/10 p-5">
        Optimize API Performance Discussions
      </div>

      <div className="rounded-2xl bg-red-500/10 p-5">
        Explain Edge Cases More Clearly
      </div>

    </div>

  </div>

</div>

{/* AI Feedback */}

<div
  className="
    mt-10
    rounded-[32px]
    border
    border-white/10
    bg-white/[0.03]
    backdrop-blur-xl
    p-10
  "
>

  <h2 className="text-3xl font-bold">
    AI Interview Feedback
  </h2>

  <p className="mt-6 text-zinc-400 leading-8">

    You demonstrated excellent communication
    throughout the interview and maintained a
    clear thought process while answering
    technical questions.

    <br /><br />

    Your explanations were well structured and
    easy to follow. Strengthening your System
    Design knowledge and discussing edge cases
    in greater detail will significantly improve
    your interview performance.

    <br /><br />

    Overall, you are well prepared for
    software engineering interviews.

  </p>

</div>

{/* Bottom Buttons */}

<div className="flex flex-wrap justify-center gap-5 mt-12">

  <button

    onClick={() =>
      navigate("/dashboard")
    }

    className="
      rounded-2xl
      border
      border-white/10
      bg-white/5
      px-8
      py-4
      hover:bg-white/10
      transition
    "

  >

    Dashboard

  </button>

  <button

    onClick={() =>
      navigate("/interview/setup")
    }

    className="
      rounded-2xl
      bg-white
      px-8
      py-4
      text-black
      font-semibold
    "

  >

    Retake Interview

  </button>

</div>

      </main>

    </div>

  );

}